### ISSUE TITLE
ripple test faucet

### ISSUE THREAD

**Issue by kiahmed** [ripple/rippled#2394]
can someone name a ripple faucet that works? I need some test ripple on this address

r3AeoS4gedy7YY6icSL61wGMZfjwMoBV4y

**Comment by passionofvc** [comment]
hi @kiahmed 
you can use http://ripplerm.github.io/ripple-wallet/
for test payment tx.

**Comment by kiahmed** [comment]
did try that tool. looks like it can't send , got this error. Also, couldn't find the tx in explorer 

Sending 20 XRP to rnSsPiFqjyRX9bagm5LExHmXExyX7fBNzo 
Status:[FINAL, tejMaxLedger], Result: tefMASTER_DISABLED 
tx_hash: 49B2C2FA0D04FD16957DDB920ABC4C763704789C62A19F478C195840EA472FB9

**Comment by passionofvc** [comment]
hi @kiahmed 
get new address test  from https://ripple.com/build/xrp-test-net/,
update address and secret to you new test address,
and send to you new funding address from it,
this is only for test, do not use it for sending in main net.

**Comment by kiahmed** [comment]
@passionofvc I did all that and was able to make a successful tx here is the hash 83A859E91E5DB994577E2D1FB9B23A7A6CC1062CA979D29BC9CDABBC6F6C37C7  for destination r3AeoS4gedy7YY6icSL61wGMZfjwMoBV4y 

unfortunately , when I query balance or account_info, or account_tx command it errors saying account don't exit almost 40 mins after transaction

**Comment by passionofvc** [comment]
@kiahmed 
it seems your transaction failed with tecNO_DST.
does [currency:  "XPR"]  ok for currency?
I think it must be XRP for payment transactions.

```
 2018-02-23, 08:26:21 Failed transaction
Hash: 83A859E91E5DB994577E2D1FB9B23A7A6CC1062CA979D29BC9CDABBC6F6C37C7 

Raw Tx:
 Object
Account:  "rBcqzVptDrcLvgrbTsbmejcGzD8GExfNR1"
 Amount: Object
currency:  "XPR"
issuer:  "rBcqzVptDrcLvgrbTsbmejcGzD8GExfNR1"
value:  "20"
Destination:  "r3AeoS4gedy7YY6icSL61wGMZfjwMoBV4y"
Fee:  "10"
Flags: 2147483648
Sequence: 1
SigningPubKey:  "039DA7135DE89B52A15DA69BBDCDC7E6E1CF296ABF0606721DBC137ED633C6D8EE"
TransactionType:  "Payment"
TxnSignature:  "3045022100FD9ABEA9BE48394CD85892B56CA61FC59369F2175F1F9823EB939E446CDC7904022044374908BF2F507D7114D4B51DF16666A50F475BA41B7919CE8A26D58496E67C"
date: 572657181
hash:  "83A859E91E5DB994577E2D1FB9B23A7A6CC1062CA979D29BC9CDABBC6F6C37C7"
inLedger: 6941051
ledger_index: 6941051

Meta:
 Object
 AffectedNodes: Array [1]
 0: Object
 ModifiedNode: Object
 FinalFields: Object
LedgerEntryType:  "AccountRoot"
LedgerIndex:  "412B886710EC27F0ABE185328F872B0AADA4D960F3AD960192CB187CDD102220"
 PreviousFields: Object
PreviousTxnID:  "C80FF77D94EEB85587A09FDB810BAA3B39ABA6E194352DDB41978A8FA887751B"
PreviousTxnLgrSeq: 6880943
TransactionIndex: 4
TransactionResult:  "tecNO_DST"
```
